spring:
  ####静态资源匹配
  mvc:
    static-path-pattern: /**
  resources:
    ####静态资源路径
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:${web.upload.path},classpath:static/,file:static/
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


web:
  upload:
    path: /Users/edz/upload2
unicom:
  checkFile:
    check:
      hosts: http://localhost:8080
    save:
      hosts: http://10.2.29.228:9002
      paramName: file
    type_0: objPermisApplyValid
    type_1: appAcWhiteApplyValid