spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gitwsl/springcloud-config.git
          username: gitwsl
          password: 571035128wang
          search-paths: config-repo
server:
  port: 9090